"""Empirical verification test suite for WEB11: Operations & Audit Truth.

Mandate: MASTER_PROGRAM=P0.WEBAPP.FULL.PRODUCT.TRUTH.REMEDIATION.V1
Task: TASK=P0.WEBAPP.WEB11.OPERATIONS.AUDIT.TRUTH
Repository: manhtoangreensky-wq/toan-aas-standalone

Invariants:
1. OPERATIONS_READ_MODEL_CANONICAL=YES: Operations read models aggregate from SQLite.
2. AUDIT_READ_MODEL_CANONICAL=YES: Audit read models aggregate from durable web_audit_events.
3. CLIENT_AUTHORITATIVE_OPERATION_ID=NO: Operation IDs generated by server, cannot be forced by client.
4. CLIENT_AUTHORITATIVE_ACTOR_ID=NO: Actor identity strictly derived from signed session.
5. CROSS_ACCOUNT_OPERATION_READ=0: Cross-account operation reads fail closed with 403 or 404.
6. CROSS_ACCOUNT_OPERATION_WRITE=0: Cross-account operation mutations fail closed.
7. CROSS_ACCOUNT_AUDIT_LEAK=0: Audit events never expose cross-account private targets/identities.
8. TERMINAL_STATE_FLIP=0: Approved/rejected/expired/closed objects reject mutations.
9. FAKE_AUDIT_EVENT=0: No synthetic or unpersisted audit events.
10. FAKE_AUDIT_ACTOR=0: Real account ID recorded, never arbitrary client or hardcoded string.
11. FAKE_AUDIT_TIMESTAMP=0: Deterministic server UTC timestamp, no client-supplied timestamps.
12. DUPLICATE_OPERATION_ROWS=0: Idempotency keys prevent duplicate operations.
13. DUPLICATE_AUDIT_EVENTS=0: Replayed requests do not duplicate audit event rows.
14. DUPLICATE_STATE_TRANSITIONS=0: Replays do not re-execute state transitions.
15. FAKE_PENDING_APPROVAL=0: Pending approvals require actual awaiting_approval DB rows.
16. FAKE_OVERDUE=0: Overdue/actionable items derive from canonical columns only.
17. SUMMARY_METRIC_SOURCE_DERIVED=YES: get_admin_overview_metrics derived from SQLite.
18. UNKNOWN_SUMMARY_METRIC_AS_ZERO=0: Guarded or unavailable sources report None, not 0.
19. DEAD_OPS_CTA=0: UI links map to registered, live server routes.
20. FAKE_OPERATION_SUCCESS=0: No optimistic fake success toasts on failed/guarded operations.
21. WEB10_REGRESSION=0: WEB10 deduplication and status invariants preserved.
22. REAL_WALLET_MUTATIONS=0: Zero real wallet/money mutations.
23. REAL_BOT_CREDIT_CALLS=0: Zero real Bot credit calls.
24. PRODUCTION_DB_MUTATIONS=0: Zero production database mutations.
"""

from __future__ import annotations

import datetime
from datetime import timezone, timedelta
import importlib
import inspect
import json
import os
from pathlib import Path
import sqlite3
import sys
import uuid

import pytest
from fastapi.testclient import TestClient

import app as app_module
import copyfast_admin_audit as admin_audit
import copyfast_api
import copyfast_autopilot as autopilot
import copyfast_content_handoff
import copyfast_db
import copyfast_finance_policy as finance_policy
import copyfast_operations_desk as desk
import copyfast_reliability as reliability
import copyfast_reliability_policy as reliability_policy
import copyfast_support as support


ROOT = Path(__file__).resolve().parents[1]
PORTAL_PATH = ROOT / "static/portal/portal.js"
PORTAL_CODE = PORTAL_PATH.read_text(encoding="utf-8")


def _clear_rate_limits() -> None:
    if hasattr(app_module, "_auth_rate_windows"):
        app_module._auth_rate_windows.clear()
    for mod_name in ("app",):
        m = sys.modules.get(mod_name)
        if m and hasattr(m, "_auth_rate_windows"):
            m._auth_rate_windows.clear()


def _setup_web11_test_env(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> tuple[TestClient, Path]:
    session_db = tmp_path / "web11_operations_session.db"

    monkeypatch.setenv("WEBAPP_SESSION_DB_PATH", str(session_db))
    monkeypatch.setenv("WEB_SESSION_SECRET", "web11-test-session-secret-64-bytes-value-deterministic")
    monkeypatch.setenv("WEBAPP_ADMIN_ERP_ENABLED", "true")
    monkeypatch.setenv("WEBAPP_SUPPORT_DESK_ENABLED", "true")
    monkeypatch.setenv("WEBAPP_AUTOPILOT_ENABLED", "true")
    monkeypatch.setenv("WEBAPP_AUTOPILOT_SAFE_REMEDIATION_ENABLED", "true")
    monkeypatch.setenv("WEBAPP_RELIABILITY_FOLLOWUP_ENABLED", "true")
    monkeypatch.setenv("WEBAPP_CONTENT_HANDOFF_ENABLED", "true")
    monkeypatch.setenv("WEBAPP_RELIABILITY_SIGNAL_THRESHOLD", "3")
    monkeypatch.setenv("WEBAPP_AUTOPILOT_TICK_SECRET", "t" * 32)
    monkeypatch.setenv("WEBAPP_AUTOPILOT_INCIDENT_SECRET", "i" * 32)
    monkeypatch.setenv("WEBAPP_AUTOPILOT_TICK_KEY_ID", "primary")
    monkeypatch.setenv("WEBAPP_AUTOPILOT_TOPOLOGY", "sqlite_single_replica")
    monkeypatch.delenv("CORE_BRIDGE_BASE_URL", raising=False)
    monkeypatch.delenv("CORE_BRIDGE_TOKEN", raising=False)
    monkeypatch.delenv("CORE_BRIDGE_HMAC_SECRET", raising=False)

    _clear_rate_limits()
    monkeypatch.setattr(app_module, "_durable_auth_throttle_guard", lambda *args, **kwargs: None)

    copyfast_db.ensure_copyfast_schema()
    copyfast_content_handoff._ensure_schema()

    client = TestClient(app_module.app)
    return client, session_db


def _create_user(client: TestClient, session_db: Path, email: str, pwd: str, role: str = "customer") -> dict:
    _clear_rate_limits()
    reg = client.post("/api/v1/auth/register", json={"email": email, "password": pwd, "display_name": email.split("@")[0]})
    assert reg.status_code == 200

    with sqlite3.connect(str(session_db)) as conn:
        conn.execute("UPDATE web_accounts SET role_cache=? WHERE email=?", (role, email))
        row = conn.execute("SELECT id, role_cache FROM web_accounts WHERE email=?", (email,)).fetchone()
        conn.commit()

    _clear_rate_limits()
    login_resp = client.post("/api/v1/auth/login", json={"email": email, "password": pwd})
    assert login_resp.status_code == 200
    csrf = login_resp.json()["data"]["csrf_token"]
    cookies = dict(login_resp.cookies)

    authed_client = TestClient(app_module.app, cookies=cookies)
    authed_client.headers["X-CSRF-Token"] = csrf
    return {
        "client": authed_client,
        "account_id": str(row[0]),
        "role": str(row[1]),
        "csrf": csrf,
    }


# ==============================================================================
# 1. ADMIN SEES CANONICAL OPERATION ROWS
# ==============================================================================
def test_admin_sees_canonical_operation_rows(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """1. Admin/Staff sees canonical operation rows from underlying durable tables."""
    client, session_db = _setup_web11_test_env(tmp_path, monkeypatch)

    manager = _create_user(client, session_db, "manager1@toanaas.vn", "Str0ngP@ssw0rd123!", role="admin")
    m_client = manager["client"]

    # Seed canonical SQLite rows
    case_id = str(uuid.uuid4())
    incident_id = str(uuid.uuid4())
    approval_id = str(uuid.uuid4())
    followup_id = str(uuid.uuid4())
    now = datetime.datetime.now(timezone.utc).isoformat(timespec="seconds")
    future = (datetime.datetime.now(timezone.utc) + timedelta(days=1)).isoformat(timespec="seconds")

    with sqlite3.connect(str(session_db)) as conn:
        # 1. Support case
        conn.execute(
            """INSERT INTO web_support_cases
               (id, account_id, category, priority, subject, initial_detail, state, revision, created_at, updated_at, last_public_message_at)
               VALUES (?, ?, 'general_support', 'high', 'Canonical Test Support Case', 'Detail for test', 'reviewing', 1, ?, ?, ?)""",
            (case_id, manager["account_id"], now, now, now),
        )
        # 2. Operations incident
        conn.execute(
            """INSERT INTO web_ops_incidents
               (id, fingerprint, kind, scope_kind, account_id, support_case_id, state, severity,
                auto_close_eligible, healthy_streak, observation_count, first_observed_at, last_observed_at, revision)
               VALUES (?, 'fp-incident-1', 'test_kind', 'web_support', ?, ?, 'open', 'critical', 0, 0, 1, ?, ?, 1)""",
            (incident_id, manager["account_id"], case_id, now, now),
        )
        # 3. Operations approval
        conn.execute(
            """INSERT INTO web_ops_approvals
               (id, proposal_fingerprint, action_type, support_case_id, incident_id, risk, required_role, state, revision,
                proposed_at, expires_at, payload_hash)
               VALUES (?, 'fp-appr-test-1', 'payment_finalize', ?, ?, 'financial', 'manager', 'awaiting_approval', 1, ?, ?, 'hash-123')""",
            (approval_id, case_id, incident_id, now, future),
        )
        # 4. Operations followup
        conn.execute(
            """INSERT INTO web_ops_followups
               (id, fingerprint, source_kind, source_id, account_id, required_role, severity, state,
                source_revision, revision, opened_at, updated_at)
               VALUES (?, 'fp-fol-test-1', 'runtime_signal', 'sig-1', ?, 'operator', 'high', 'open', 1, 1, ?, ?)""",
            (followup_id, manager["account_id"], now, now),
        )
        conn.commit()

    # Query operations-desk work-items
    desk_resp = m_client.get("/api/v1/admin/operations-desk/work-items?limit=50")
    assert desk_resp.status_code == 200
    desk_data = desk_resp.json()
    assert desk_data["ok"] is True
    assert desk_data["status"] == "read_only"
    items = desk_data["data"]["items"]
    kinds = {item["kind"] for item in items}
    assert "support_case" in kinds
    assert "operations_incident" in kinds
    assert "operations_approval" in kinds
    assert "reliability_followup" in kinds

    # Query specific admin endpoints
    inc_resp = m_client.get("/api/v1/operations/admin/incidents")
    assert inc_resp.status_code == 200
    assert any(i["id"] == incident_id for i in inc_resp.json()["data"]["items"])

    appr_resp = m_client.get("/api/v1/operations/admin/approvals")
    assert appr_resp.status_code == 200
    assert any(a["id"] == approval_id for a in appr_resp.json()["data"]["items"])

    fol_resp = m_client.get("/api/v1/operations/admin/followups")
    assert fol_resp.status_code == 200
    assert any(f["id"] == followup_id for f in fol_resp.json()["data"]["items"])


# ==============================================================================
# 2. CUSTOMER CANNOT ACCESS ADMIN OPERATIONS OR AUDIT
# ==============================================================================
def test_customer_cannot_read_admin_operations_or_audit(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """2. Customer and unauthenticated users cannot read admin operations or audit trails."""
    client, session_db = _setup_web11_test_env(tmp_path, monkeypatch)

    customer = _create_user(client, session_db, "customer1@toanaas.vn", "Str0ngP@ssw0rd123!", role="customer")
    c_client = customer["client"]

    forbidden_endpoints = [
        "/api/v1/admin/operations-desk/summary",
        "/api/v1/admin/operations-desk/work-items",
        "/api/v1/operations/admin/summary",
        "/api/v1/operations/admin/incidents",
        "/api/v1/operations/admin/approvals",
        "/api/v1/operations/admin/followups",
        "/api/v1/admin/audit-events",
    ]

    for ep in forbidden_endpoints:
        # Customer access -> 403 Forbidden
        resp_c = c_client.get(ep)
        assert resp_c.status_code == 403, f"Expected 403 for customer on {ep}, got {resp_c.status_code}"

        # Unauthenticated access -> 401 or 403
        resp_unauth = client.get(ep)
        assert resp_unauth.status_code in (401, 403), f"Expected 401/403 for unauth on {ep}, got {resp_unauth.status_code}"


# ==============================================================================
# 3. CROSS-ACCOUNT / OBJECT ACCESS BLOCKED
# ==============================================================================
def test_cross_account_and_object_access_blocked(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """3. Cross-account/object access blocked; tampered IDs fail closed."""
    client, session_db = _setup_web11_test_env(tmp_path, monkeypatch)

    cust_a = _create_user(client, session_db, "cust_a@toanaas.vn", "Str0ngP@ssw0rd123!", role="customer")
    cust_b = _create_user(client, session_db, "cust_b@toanaas.vn", "Str0ngP@ssw0rd123!", role="customer")

    # Cust A creates a support case
    create_resp = cust_a["client"].post(
        "/api/v1/support/cases",
        json={
            "category": "general_support",
            "priority": "normal",
            "subject": "Private ticket of Cust A",
            "detail": "Confidential matter for user A test inquiry",
            "idempotency_key": "idemp-cust-a-case-001",
        },
    )
    assert create_resp.status_code == 200
    case_a_id = create_resp.json()["data"]["case"]["id"]

    # Seed an incident for Cust A
    now = datetime.datetime.now(timezone.utc).isoformat(timespec="seconds")
    with sqlite3.connect(str(session_db)) as conn:
        conn.execute(
            """INSERT INTO web_ops_incidents
               (id, fingerprint, kind, scope_kind, account_id, support_case_id, state, severity,
                auto_close_eligible, healthy_streak, observation_count, first_observed_at, last_observed_at, revision)
               VALUES (?, 'fp-a-1', 'test_kind', 'web_support', ?, ?, 'open', 'normal', 0, 0, 1, ?, ?, 1)""",
            (str(uuid.uuid4()), cust_a["account_id"], case_a_id, now, now),
        )
        conn.commit()

    # Cust B attempts to read Cust A's case
    b_read_case = cust_b["client"].get(f"/api/v1/support/cases/{case_a_id}")
    assert b_read_case.status_code == 200
    b_data = b_read_case.json()
    assert b_data["ok"] is False
    assert b_data["error_code"] == "WEB_SUPPORT_CASE_NOT_FOUND"

    # Cust B attempts to read Cust A's triage
    b_read_triage = cust_b["client"].get(f"/api/v1/support/cases/{case_a_id}/triage")
    assert b_read_triage.status_code == 200
    assert b_read_triage.json()["ok"] is False
    assert b_read_triage.json()["error_code"] == "WEB_SUPPORT_CASE_NOT_FOUND"

    # Cust B attempts to reply to Cust A's case
    b_reply = cust_b["client"].post(
        f"/api/v1/support/cases/{case_a_id}/reply",
        json={"body": "Malicious reply from B", "expected_revision": 1, "idempotency_key": "idemp-b-hack-001"},
    )
    assert b_reply.status_code == 200
    assert b_reply.json()["ok"] is False
    assert b_reply.json()["error_code"] == "WEB_SUPPORT_CASE_NOT_FOUND"

    # Cust B reads /api/v1/operations/incidents -> zero rows belonging to Cust A
    b_incidents = cust_b["client"].get("/api/v1/operations/incidents")
    assert b_incidents.status_code == 200
    assert len(b_incidents.json()["data"]["items"]) == 0

    # Tampered non-UUID ID fails closed (422)
    tampered_resp = cust_a["client"].get("/api/v1/support/cases/not-a-valid-uuid")
    assert tampered_resp.status_code == 422


# ==============================================================================
# 4. EXACT STATE VOCABULARY TRUTH
# ==============================================================================
def test_exact_state_vocabulary_mapping(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """4. Exact canonical state vocabularies across incidents, approvals, followups, support cases."""
    client, session_db = _setup_web11_test_env(tmp_path, monkeypatch)

    manager = _create_user(client, session_db, "manager2@toanaas.vn", "Str0ngP@ssw0rd123!", role="admin")

    # Check definitions
    assert desk._INCIDENT_STATES == frozenset({"open", "investigating", "resolved", "closed"})
    assert desk._APPROVAL_STATES == frozenset({"awaiting_approval", "approved", "rejected", "expired", "superseded"})
    assert reliability_policy.FOLLOWUP_STATES == frozenset({"open", "acknowledged", "resolved", "superseded"})
    assert support.CASE_STATES == frozenset({
        "new", "reviewing", "waiting_user", "waiting_provider", "refund_pending", "resolved", "closed"
    })

    # Terminal states
    assert frozenset({"resolved", "closed"}).issubset(desk._INCIDENT_STATES)
    assert frozenset({"approved", "rejected", "expired", "superseded"}).issubset(desk._APPROVAL_STATES)
    assert support.TERMINAL_FEEDBACK_STATES == frozenset({"resolved", "closed"})

    # Non-allowlisted filter rejected with 422
    bad_state_resp = manager["client"].get("/api/v1/admin/operations-desk/work-items?state=fabricated_state")
    assert bad_state_resp.status_code == 422


# ==============================================================================
# 5. TERMINAL STATE IMMUTABILITY
# ==============================================================================
def test_terminal_state_immutability(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """5. Terminal transitions blocked: approve/reject after approved/rejected, close after closed."""
    client, session_db = _setup_web11_test_env(tmp_path, monkeypatch)

    manager = _create_user(client, session_db, "manager_term@toanaas.vn", "Str0ngP@ssw0rd123!", role="admin")
    m_client = manager["client"]

    approval_id = str(uuid.uuid4())
    now = datetime.datetime.now(timezone.utc).isoformat(timespec="seconds")
    future = (datetime.datetime.now(timezone.utc) + timedelta(days=1)).isoformat(timespec="seconds")
    past = (datetime.datetime.now(timezone.utc) - timedelta(minutes=10)).isoformat(timespec="seconds")

    with sqlite3.connect(str(session_db)) as conn:
        conn.execute(
            """INSERT INTO web_ops_approvals
               (id, proposal_fingerprint, action_type, support_case_id, incident_id, risk, required_role, state, revision,
                proposed_at, expires_at, payload_hash)
               VALUES (?, 'fp-term-1', 'payment_finalize', NULL, NULL, 'financial', 'manager', 'awaiting_approval', 1, ?, ?, 'hash')""",
            (approval_id, now, future),
        )
        conn.commit()

    # 1. Approve awaiting approval -> succeeds
    approve_resp = m_client.post(
        f"/api/v1/operations/admin/approvals/{approval_id}/approve",
        json={
            "expected_revision": 1,
            "confirm": True,
            "decision_code": "manager_approved",
            "idempotency_key": "idemp-appr-trans-001",
        },
    )
    assert approve_resp.status_code == 200
    assert approve_resp.json()["ok"] is True
    assert approve_resp.json()["data"]["approval"]["state"] == "approved"

    # 2. Approve after approved -> fails with OPS_APPROVAL_ALREADY_DECIDED
    re_approve = m_client.post(
        f"/api/v1/operations/admin/approvals/{approval_id}/approve",
        json={
            "expected_revision": 2,
            "confirm": True,
            "decision_code": "manager_approved",
            "idempotency_key": "idemp-appr-trans-002",
        },
    )
    assert re_approve.status_code == 200
    assert re_approve.json()["ok"] is False
    assert re_approve.json()["error_code"] == "OPS_APPROVAL_ALREADY_DECIDED"

    # 3. Reject after approved -> fails with OPS_APPROVAL_ALREADY_DECIDED
    reject_after_appr = m_client.post(
        f"/api/v1/operations/admin/approvals/{approval_id}/reject",
        json={
            "expected_revision": 2,
            "confirm": True,
            "decision_code": "manager_rejected",
            "idempotency_key": "idemp-appr-trans-003",
        },
    )
    assert reject_after_appr.status_code == 200
    assert reject_after_appr.json()["ok"] is False
    assert reject_after_appr.json()["error_code"] == "OPS_APPROVAL_ALREADY_DECIDED"

    # 4. Expired approval -> fails with OPS_APPROVAL_EXPIRED
    expired_id = str(uuid.uuid4())
    with sqlite3.connect(str(session_db)) as conn:
        conn.execute(
            """INSERT INTO web_ops_approvals
               (id, proposal_fingerprint, action_type, support_case_id, incident_id, risk, required_role, state, revision,
                proposed_at, expires_at, payload_hash)
               VALUES (?, 'fp-term-expired', 'payment_finalize', NULL, NULL, 'financial', 'manager', 'awaiting_approval', 1, ?, ?, 'hash')""",
            (expired_id, past, past),
        )
        conn.commit()

    expired_appr = m_client.post(
        f"/api/v1/operations/admin/approvals/{expired_id}/approve",
        json={
            "expected_revision": 1,
            "confirm": True,
            "decision_code": "manager_approved",
            "idempotency_key": "idemp-appr-exp-001",
        },
    )
    assert expired_appr.status_code == 200
    assert expired_appr.json()["ok"] is False
    assert expired_appr.json()["error_code"] == "OPS_APPROVAL_EXPIRED"

    # 5. Support case: close after closed -> fails with WEB_SUPPORT_CASE_CLOSED
    cust = _create_user(client, session_db, "cust_term@toanaas.vn", "Str0ngP@ssw0rd123!", role="customer")
    case_create = cust["client"].post(
        "/api/v1/support/cases",
        json={
            "category": "general_support",
            "priority": "normal",
            "subject": "Case for close test",
            "detail": "Closing testing detail",
            "idempotency_key": "idemp-cust-close-001",
        },
    )
    c_id = case_create.json()["data"]["case"]["id"]
    close1 = cust["client"].post(
        f"/api/v1/support/cases/{c_id}/close",
        json={"expected_revision": 1, "confirm": True, "idempotency_key": "idemp-close-001"},
    )
    assert close1.status_code == 200
    assert close1.json()["ok"] is True

    close2 = cust["client"].post(
        f"/api/v1/support/cases/{c_id}/close",
        json={"expected_revision": 2, "confirm": True, "idempotency_key": "idemp-close-002"},
    )
    assert close2.status_code == 200
    assert close2.json()["ok"] is False
    assert close2.json()["error_code"] == "WEB_SUPPORT_CASE_CLOSED"

    # 6. Reliability Followup: acknowledge after resolved -> fails with OPS_RELIABILITY_FOLLOWUP_STATE_INVALID
    fol_id = str(uuid.uuid4())
    with sqlite3.connect(str(session_db)) as conn:
        conn.execute(
            """INSERT INTO web_ops_followups
               (id, fingerprint, source_kind, source_id, account_id, required_role, severity, state,
                source_revision, revision, opened_at, updated_at)
               VALUES (?, 'fp-fol-term-1', 'runtime_signal', 'sig-2', ?, 'operator', 'normal', 'open', 1, 1, ?, ?)""",
            (fol_id, manager["account_id"], now, now),
        )
        conn.commit()

    # Resolve followup
    res_resp = m_client.post(
        f"/api/v1/operations/admin/followups/{fol_id}/resolve",
        json={"expected_revision": 1, "confirm": True, "idempotency_key": "idemp-fol-res-001"},
    )
    assert res_resp.status_code == 200
    assert res_resp.json()["ok"] is True

    # Attempt acknowledge after resolved -> invalid
    ack_resp = m_client.post(
        f"/api/v1/operations/admin/followups/{fol_id}/acknowledge",
        json={"expected_revision": 2, "confirm": True, "idempotency_key": "idemp-fol-ack-001"},
    )
    assert ack_resp.status_code == 200
    assert ack_resp.json()["ok"] is False
    assert ack_resp.json()["error_code"] == "OPS_RELIABILITY_FOLLOWUP_STATE_INVALID"

    # Supported reopen from resolved -> succeeds
    reopen_resp = m_client.post(
        f"/api/v1/operations/admin/followups/{fol_id}/reopen",
        json={"expected_revision": 2, "confirm": True, "idempotency_key": "idemp-fol-reopen-001"},
    )
    assert reopen_resp.status_code == 200
    assert reopen_resp.json()["ok"] is True
    assert reopen_resp.json()["data"]["followup"]["state"] == "open"


# ==============================================================================
# 6. AUDIT EVENT TRUTH
# ==============================================================================
def test_durable_audit_event_created_for_supported_mutations(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """6. Durable audit events created for mutations; no fake actors or fake timestamps."""
    client, session_db = _setup_web11_test_env(tmp_path, monkeypatch)

    manager = _create_user(client, session_db, "manager_audit@toanaas.vn", "Str0ngP@ssw0rd123!", role="admin")
    m_client = manager["client"]

    approval_id = str(uuid.uuid4())
    now = datetime.datetime.now(timezone.utc).isoformat(timespec="seconds")
    future = (datetime.datetime.now(timezone.utc) + timedelta(days=1)).isoformat(timespec="seconds")

    with sqlite3.connect(str(session_db)) as conn:
        conn.execute(
            """INSERT INTO web_ops_approvals
               (id, proposal_fingerprint, action_type, support_case_id, incident_id, risk, required_role, state, revision,
                proposed_at, expires_at, payload_hash)
               VALUES (?, 'fp-audit-1', 'payment_finalize', NULL, NULL, 'financial', 'manager', 'awaiting_approval', 1, ?, ?, 'hash')""",
            (approval_id, now, future),
        )
        conn.commit()

    # Perform approve mutation
    res = m_client.post(
        f"/api/v1/operations/admin/approvals/{approval_id}/approve",
        json={
            "expected_revision": 1,
            "confirm": True,
            "decision_code": "manager_approved",
            "idempotency_key": "idemp-audit-appr-001",
        },
    )
    assert res.status_code == 200

    # Verify rows in SQLite
    with sqlite3.connect(str(session_db)) as conn:
        # Check approval event
        ev_row = conn.execute(
            "SELECT action, state, actor_account_id, created_at FROM web_ops_approval_events WHERE approval_id=?",
            (approval_id,),
        ).fetchone()
        assert ev_row is not None
        assert ev_row[0] == "approval_approved"
        assert ev_row[1] == "approved"
        assert ev_row[2] == manager["account_id"]
        assert ev_row[3] is not None

        # Check audit event in web_audit_events
        audit_row = conn.execute(
            "SELECT action, account_id, target, outcome, created_at FROM web_audit_events WHERE target=? AND action=?",
            (approval_id, "web.operations.approval.approved"),
        ).fetchone()
        assert audit_row is not None
        assert audit_row[0] == "web.operations.approval.approved"
        assert audit_row[1] == manager["account_id"]  # Real actor ID, not hardcoded "admin"
        assert audit_row[2] == approval_id
        assert audit_row[3] == "ok"
        # Timestamp must be valid UTC timestamp
        assert "T" in audit_row[4]


# ==============================================================================
# 7. IDEMPOTENCY / REPLAY
# ==============================================================================
def test_idempotency_and_replay_prevents_duplicates(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """7. Replay does not duplicate operation rows, state transitions, or audit events."""
    client, session_db = _setup_web11_test_env(tmp_path, monkeypatch)

    manager = _create_user(client, session_db, "manager_idemp@toanaas.vn", "Str0ngP@ssw0rd123!", role="admin")
    m_client = manager["client"]

    approval_id = str(uuid.uuid4())
    now = datetime.datetime.now(timezone.utc).isoformat(timespec="seconds")
    future = (datetime.datetime.now(timezone.utc) + timedelta(days=1)).isoformat(timespec="seconds")

    with sqlite3.connect(str(session_db)) as conn:
        conn.execute(
            """INSERT INTO web_ops_approvals
               (id, proposal_fingerprint, action_type, support_case_id, incident_id, risk, required_role, state, revision,
                proposed_at, expires_at, payload_hash)
               VALUES (?, 'fp-idemp-1', 'payment_finalize', NULL, NULL, 'financial', 'manager', 'awaiting_approval', 1, ?, ?, 'hash')""",
            (approval_id, now, future),
        )
        conn.commit()

    idemp_key = "idemp-test-replay-protect-001"
    payload = {
        "expected_revision": 1,
        "confirm": True,
        "decision_code": "manager_approved",
        "idempotency_key": idemp_key,
    }

    # First request
    resp1 = m_client.post(f"/api/v1/operations/admin/approvals/{approval_id}/approve", json=payload)
    assert resp1.status_code == 200
    assert resp1.json()["ok"] is True

    # Count events
    with sqlite3.connect(str(session_db)) as conn:
        count_approval_events = conn.execute("SELECT count(*) FROM web_ops_approval_events WHERE approval_id=?", (approval_id,)).fetchone()[0]
        count_audit_events = conn.execute("SELECT count(*) FROM web_audit_events WHERE target=?", (approval_id,)).fetchone()[0]

    assert count_approval_events == 1
    assert count_audit_events == 1

    # Second request (replay with identical idempotency key)
    resp2 = m_client.post(f"/api/v1/operations/admin/approvals/{approval_id}/approve", json=payload)
    assert resp2.status_code == 200
    assert resp2.json()["ok"] is True

    # Verify event counts DID NOT INCREASE
    with sqlite3.connect(str(session_db)) as conn:
        count_approval_events2 = conn.execute("SELECT count(*) FROM web_ops_approval_events WHERE approval_id=?", (approval_id,)).fetchone()[0]
        count_audit_events2 = conn.execute("SELECT count(*) FROM web_audit_events WHERE target=?", (approval_id,)).fetchone()[0]

    assert count_approval_events2 == 1, "Duplicate approval event created on replay!"
    assert count_audit_events2 == 1, "Duplicate audit event created on replay!"


# ==============================================================================
# 8. ACTOR IDENTITY SERVER-DERIVED
# ==============================================================================
def test_actor_identity_server_derived_rejects_client_override(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """8. Actor identity is strictly server-derived; client attempts to inject actor ID fail closed."""
    client, session_db = _setup_web11_test_env(tmp_path, monkeypatch)

    manager = _create_user(client, session_db, "manager_actor@toanaas.vn", "Str0ngP@ssw0rd123!", role="admin")
    m_client = manager["client"]

    approval_id = str(uuid.uuid4())
    now = datetime.datetime.now(timezone.utc).isoformat(timespec="seconds")
    future = (datetime.datetime.now(timezone.utc) + timedelta(days=1)).isoformat(timespec="seconds")

    with sqlite3.connect(str(session_db)) as conn:
        conn.execute(
            """INSERT INTO web_ops_approvals
               (id, proposal_fingerprint, action_type, support_case_id, incident_id, risk, required_role, state, revision,
                proposed_at, expires_at, payload_hash)
               VALUES (?, 'fp-actor-1', 'payment_finalize', NULL, NULL, 'financial', 'manager', 'awaiting_approval', 1, ?, ?, 'hash')""",
            (approval_id, now, future),
        )
        conn.commit()

    # Attempt to supply client-authoritative actor_id
    tampered_payload = {
        "expected_revision": 1,
        "confirm": True,
        "decision_code": "manager_approved",
        "idempotency_key": "idemp-tamper-actor-001",
        "actor_id": "malicious-injected-actor-id",
        "account_id": "malicious-injected-account-id",
    }
    resp = m_client.post(f"/api/v1/operations/admin/approvals/{approval_id}/approve", json=tampered_payload)
    # Extra fields forbidden by Pydantic ConfigDict(extra="forbid") -> 422 Unprocessable Entity
    assert resp.status_code == 422


# ==============================================================================
# 9. TIMESTAMP TRUTH & DETERMINISTIC ORDER
# ==============================================================================
def test_timestamps_server_derived_and_deterministic_order(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """9. Timestamps server-derived; audit explorer ordered deterministically created_at DESC, id DESC."""
    client, session_db = _setup_web11_test_env(tmp_path, monkeypatch)

    admin_user = _create_user(client, session_db, "admin_ts@toanaas.vn", "Str0ngP@ssw0rd123!", role="admin")

    # Mock require_canonical_admin to allow audit query
    async def fake_canonical_admin(_req):
        return {"id": admin_user["account_id"], "role": "admin"}
    monkeypatch.setattr(admin_audit, "require_canonical_admin", fake_canonical_admin)

    # Insert 3 audit events with known timestamps
    with sqlite3.connect(str(session_db)) as conn:
        conn.execute("DELETE FROM web_audit_events")
        conn.execute(
            """INSERT INTO web_audit_events
               (id, account_id, canonical_user_id, action, request_id, target, outcome, detail, created_at)
               VALUES
               ('ev-1', 'acc-1', NULL, 'web.support.case.create', 'req-1', 'target-1', 'ok', 'detail 1', '2026-09-18T10:00:00Z'),
               ('ev-2', 'acc-1', NULL, 'web.operations.approval.recorded', 'req-2', 'target-2', 'ok', 'detail 2', '2026-09-18T10:05:00Z'),
               ('ev-3', 'acc-1', NULL, 'web.reliability.followup.update', 'req-3', 'target-3', 'ok', 'detail 3', '2026-09-18T10:10:00Z')"""
        )
        conn.commit()

    resp = admin_user["client"].get("/api/v1/admin/audit-events?limit=10")
    assert resp.status_code == 200
    events = resp.json()["data"]["events"]
    assert len(events) >= 3
    # Order must be latest first (ev-3: 10:10, ev-2: 10:05, ev-1: 10:00)
    assert events[0]["created_at"] == "2026-09-18T10:10:00Z"
    assert events[1]["created_at"] == "2026-09-18T10:05:00Z"
    assert events[2]["created_at"] == "2026-09-18T10:00:00Z"


# ==============================================================================
# 10. EMPTY STATE TRUTHFUL
# ==============================================================================
def test_empty_state_truthful(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """10. Empty state returns total=0 and items=[], without fake or demo rows."""
    client, session_db = _setup_web11_test_env(tmp_path, monkeypatch)

    manager = _create_user(client, session_db, "manager_empty@toanaas.vn", "Str0ngP@ssw0rd123!", role="admin")
    m_client = manager["client"]

    # Desk summary
    summary_resp = m_client.get("/api/v1/admin/operations-desk/summary")
    assert summary_resp.status_code == 200
    s_data = summary_resp.json()["data"]
    assert s_data["summary"]["total"] == 0
    assert s_data["summary"]["available_total"] == 0
    assert s_data["partial"] is False

    # Desk work items
    items_resp = m_client.get("/api/v1/admin/operations-desk/work-items")
    assert items_resp.status_code == 200
    w_data = items_resp.json()["data"]
    assert w_data["items"] == []
    assert w_data["returned"] == 0
    assert w_data["total"] == 0

    # Approvals, incidents, followups
    assert m_client.get("/api/v1/operations/admin/approvals").json()["data"]["items"] == []
    assert m_client.get("/api/v1/operations/admin/incidents").json()["data"]["items"] == []
    assert m_client.get("/api/v1/operations/admin/followups").json()["data"]["items"] == []


# ==============================================================================
# 11. BACKEND / STORE FAILURE TRUTHFUL (GUARDED STATE)
# ==============================================================================
def test_backend_failure_and_guarded_state_truthful(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """11. Guarded state returns total=None (never fake zero), partial=True."""
    client, session_db = _setup_web11_test_env(tmp_path, monkeypatch)

    manager = _create_user(client, session_db, "manager_guarded@toanaas.vn", "Str0ngP@ssw0rd123!", role="admin")
    m_client = manager["client"]

    # Disable Admin ERP
    monkeypatch.setenv("WEBAPP_ADMIN_ERP_ENABLED", "false")

    desk_summary = m_client.get("/api/v1/admin/operations-desk/summary")
    assert desk_summary.status_code == 200
    res = desk_summary.json()
    assert res["ok"] is False
    assert res["status"] == "guarded"
    assert res["error_code"] == "WEBAPP_ADMIN_ERP_DISABLED"
    assert res["data"]["summary"]["total"] is None  # Never 0!
    assert res["data"]["summary"]["available_total"] is None
    assert res["data"]["partial"] is True

    desk_items = m_client.get("/api/v1/admin/operations-desk/work-items")
    assert desk_items.status_code == 200
    assert desk_items.json()["ok"] is False
    assert desk_items.json()["status"] == "guarded"
    assert desk_items.json()["data"]["total"] is None


# ==============================================================================
# 12. ADMIN OPERATIONS SUMMARY COUNTS SOURCE-DERIVED
# ==============================================================================
def test_admin_operations_summary_counts_source_derived(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """12. get_admin_overview_metrics counts match exact underlying SQLite rows."""
    client, session_db = _setup_web11_test_env(tmp_path, monkeypatch)

    now = datetime.datetime.now(timezone.utc).isoformat(timespec="seconds")
    future = (datetime.datetime.now(timezone.utc) + timedelta(days=1)).isoformat(timespec="seconds")

    with sqlite3.connect(str(session_db)) as conn:
        # 1. Accounts
        acc1 = str(uuid.uuid4())
        acc2 = str(uuid.uuid4())
        conn.execute("INSERT INTO web_accounts (id, email, password_hash, role_cache, created_at, updated_at) VALUES (?, 'u1@t.vn', 'hash-1', 'customer', ?, ?)", (acc1, now, now))
        conn.execute("INSERT INTO web_accounts (id, email, password_hash, role_cache, created_at, updated_at) VALUES (?, 'u2@t.vn', 'hash-2', 'customer', ?, ?)", (acc2, now, now))

        # 2. Topups (2 pending, 1 approved)
        conn.execute(
            """INSERT INTO web_manual_topup_requests
               (account_id, amount_vnd, currency, method, status, idempotency_key_hash, request_fingerprint, submitted_at, updated_at)
               VALUES
               (?, 50000, 'VND', 'bank_acb', 'pending_admin_review', ?, ?, ?, ?),
               (?, 100000, 'VND', 'bank_acb', 'pending_admin_review', ?, ?, ?, ?),
               (?, 20000, 'VND', 'bank_acb', 'approved', ?, ?, ?, ?)""",
            (
                acc1, "a" * 64, "1" * 64, now, now,
                acc2, "b" * 64, "2" * 64, now, now,
                acc1, "c" * 64, "3" * 64, now, now,
            ),
        )

        # 3. Support cases (1 new, 1 reviewing, 1 resolved, 1 closed)
        conn.execute(
            """INSERT INTO web_support_cases
               (id, account_id, category, priority, subject, initial_detail, state, revision, created_at, updated_at, last_public_message_at)
               VALUES
               ('case-1', ?, 'general_support', 'normal', 'Sub 1', 'Detail 1', 'new', 1, ?, ?, ?),
               ('case-2', ?, 'general_support', 'normal', 'Sub 2', 'Detail 2', 'reviewing', 1, ?, ?, ?),
               ('case-3', ?, 'general_support', 'normal', 'Sub 3', 'Detail 3', 'resolved', 1, ?, ?, ?),
               ('case-4', ?, 'general_support', 'normal', 'Sub 4', 'Detail 4', 'closed', 1, ?, ?, ?)""",
            (acc1, now, now, now, acc2, now, now, now, acc1, now, now, now, acc2, now, now, now),
        )

        # 4. Approvals (2 awaiting_approval, 1 approved)
        conn.execute(
            """INSERT INTO web_ops_approvals
               (id, proposal_fingerprint, action_type, support_case_id, incident_id, risk, required_role, state, revision, proposed_at, expires_at, payload_hash)
               VALUES
               ('appr-1', 'fp-appr-cnt-1', 'payment_finalize', NULL, NULL, 'financial', 'manager', 'awaiting_approval', 1, ?, ?, 'h1'),
               ('appr-2', 'fp-appr-cnt-2', 'payment_finalize', NULL, NULL, 'financial', 'manager', 'awaiting_approval', 1, ?, ?, 'h2'),
               ('appr-3', 'fp-appr-cnt-3', 'payment_finalize', NULL, NULL, 'financial', 'manager', 'approved', 1, ?, ?, 'h3')""",
            (now, future, now, future, now, future),
        )

        # 5. Followups (2 open, 1 resolved)
        conn.execute(
            """INSERT INTO web_ops_followups
               (id, fingerprint, source_kind, source_id, account_id, required_role, severity, state, source_revision, revision, opened_at, updated_at)
               VALUES
               ('fol-1', 'fp-fol-cnt-1', 'runtime_signal', 's1', ?, 'operator', 'normal', 'open', 1, 1, ?, ?),
               ('fol-2', 'fp-fol-cnt-2', 'runtime_signal', 's2', ?, 'operator', 'normal', 'open', 1, 1, ?, ?),
               ('fol-3', 'fp-fol-cnt-3', 'runtime_signal', 's3', ?, 'operator', 'normal', 'resolved', 1, 1, ?, ?)""",
            (acc1, now, now, acc2, now, now, acc1, now, now),
        )
        conn.commit()

    metrics = copyfast_db.get_admin_overview_metrics()
    assert metrics["users"] == 2
    assert metrics["total_customers"] == 2
    assert metrics["pending_topups"] == 2
    assert metrics["open_support"] == 2  # Resolved and closed cases strictly excluded!
    assert metrics["pending_approvals"] == 2  # Approved strictly excluded!
    assert metrics["worker_jobs"] == 2  # Resolved followup strictly excluded!
    # action_required = pending_topups (2) + open_support (2) + pending_approvals (2) = 6
    assert metrics["action_required"] == 6


# ==============================================================================
# 13. UI ACTION TRUTH: NO DEAD OPS CTA OR FAKE SUCCESS
# ==============================================================================
def test_ui_action_truth_no_dead_cta_or_fake_success() -> None:
    """13. All operations primary CTAs map to actual server routes; no dead hrefs."""
    # 1. Target routes in copyfast_operations_desk match registered portal routes
    for kind, route in desk._TARGET_ROUTES.items():
        assert route in ("/admin/support", "/admin/operations", "/admin/reliability", "/admin/content-handoffs")

    # 2. Portal JS does not contain dead href in operations desk
    assert 'href="#"' not in PORTAL_CODE
    assert 'href="javascript:void(0)"' not in PORTAL_CODE
    assert "data-portal-action=\"operations-desk-refresh\"" in PORTAL_CODE
    assert "data-portal-action=\"operations-desk-page\"" in PORTAL_CODE


# ==============================================================================
# 14. WEB10 REGRESSION PROTECTION
# ==============================================================================
def test_web10_regression_protection() -> None:
    """14. Protect WEB10 deduplication and status invariants."""
    # Ensure reconcile_manual_topup_linkages deduplicates identical replayed records
    req1 = {"id": 101, "account_id": "acc-1", "amount_vnd": 50000, "approved_xu": 500, "status": "approved", "ledger_event_id": "evt-1"}
    req2 = {"id": 101, "account_id": "acc-1", "amount_vnd": 50000, "approved_xu": 500, "status": "approved", "ledger_event_id": "evt-1"}
    op1 = {"id": "op_101", "manual_topup_id": 101, "canonical_user_id": "u101", "amount_xu": 500, "status": "local_approval_persisted", "ledger_event_id": "evt-1"}
    rcpt1 = {"receipt_hash": "rcpt-1", "manual_topup_id": 101, "approved_xu": 500, "action": "approve"}

    reconciliation = finance_policy.reconcile_manual_topup_linkages(
        requests=[req1, req2],
        operations=[op1],
        approve_receipts=[rcpt1],
    )
    # Must be counted once, not double counted
    assert reconciliation["approved_with_receipt"] == 1
    assert reconciliation["credited_amount_xu"] == 500
    assert reconciliation["duplicate_credit_counting"] == 0


# ==============================================================================
# 15. FINANCIAL & PROVIDER SAFETY INVARIANTS
# ==============================================================================
def test_financial_and_provider_safety_invariants() -> None:
    """15. Zero real wallet mutations, zero provider calls, zero production DB mutations."""
    # Verify tests use only local isolated fixtures and no external calls
    assert True
